// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstallDir() {
  return window['go']['main']['Installer']['GetInstallDir']();
}

export function Install(arg1) {
  return window['go']['main']['Installer']['Install'](arg1);
}

export function InstallInfo() {
  return window['go']['main']['Installer']['InstallInfo']();
}

export function LaunchGlean() {
  return window['go']['main']['Installer']['LaunchGlean']();
}

export function SetInstallDir(arg1) {
  return window['go']['main']['Installer']['SetInstallDir'](arg1);
}
