// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstallDir():Promise<string>;

export function Install(arg1:string):Promise<Record<string, string>>;

export function InstallInfo():Promise<Record<string, string>>;

export function LaunchGlean():Promise<void>;

export function SetInstallDir(arg1:string):Promise<void>;
