// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function DefaultSkyPath(arg1) {
  return window['go']['main']['App']['DefaultSkyPath'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteSky() {
  return window['go']['main']['App']['DeleteSky']();
}

export function ExportSky() {
  return window['go']['main']['App']['ExportSky']();
}

export function GetKnownSkies() {
  return window['go']['main']['App']['GetKnownSkies']();
}

export function GetLinks() {
  return window['go']['main']['App']['GetLinks']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetPalette() {
  return window['go']['main']['App']['GetPalette']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetSkyName() {
  return window['go']['main']['App']['GetSkyName']();
}

export function GetSkyPath() {
  return window['go']['main']['App']['GetSkyPath']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetWorkspaceState() {
  return window['go']['main']['App']['GetWorkspaceState']();
}

export function ImportImage(arg1, arg2) {
  return window['go']['main']['App']['ImportImage'](arg1, arg2);
}

export function ImportNotes(arg1) {
  return window['go']['main']['App']['ImportNotes'](arg1);
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function MigrateSky() {
  return window['go']['main']['App']['MigrateSky']();
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function OpenNote(arg1) {
  return window['go']['main']['App']['OpenNote'](arg1);
}

export function OpenSky(arg1) {
  return window['go']['main']['App']['OpenSky'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function OpenVaultFolder() {
  return window['go']['main']['App']['OpenVaultFolder']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RemoveKnownSky(arg1) {
  return window['go']['main']['App']['RemoveKnownSky'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function SaveNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SaveWorkspaceState(arg1) {
  return window['go']['main']['App']['SaveWorkspaceState'](arg1);
}

export function ScanSky() {
  return window['go']['main']['App']['ScanSky']();
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function SetupSky(arg1, arg2) {
  return window['go']['main']['App']['SetupSky'](arg1, arg2);
}

export function SkipMigration() {
  return window['go']['main']['App']['SkipMigration']();
}

export function SkyState() {
  return window['go']['main']['App']['SkyState']();
}

export function SwitchSky(arg1) {
  return window['go']['main']['App']['SwitchSky'](arg1);
}

export function WaterNote(arg1) {
  return window['go']['main']['App']['WaterNote'](arg1);
}
