// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetPalette() {
  return window['go']['main']['App']['GetPalette']();
}

export function GetSkyName() {
  return window['go']['main']['App']['GetSkyName']();
}

export function GetSkyPath() {
  return window['go']['main']['App']['GetSkyPath']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTrails() {
  return window['go']['main']['App']['GetTrails']();
}

export function GetWorkspaceState() {
  return window['go']['main']['App']['GetWorkspaceState']();
}

export function OpenNote(arg1) {
  return window['go']['main']['App']['OpenNote'](arg1);
}

export function SaveNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3);
}

export function SaveWorkspaceState(arg1) {
  return window['go']['main']['App']['SaveWorkspaceState'](arg1);
}

export function WaterNote(arg1) {
  return window['go']['main']['App']['WaterNote'](arg1);
}
