// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<main.NoteView>;

export function DefaultSkyPath(arg1:string):Promise<string>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetKnownSkies():Promise<Array<main.KnownSkyView>>;

export function GetNote(arg1:string):Promise<main.NoteView|boolean>;

export function GetNotes():Promise<Array<main.NoteView>>;

export function GetPalette():Promise<main.PaletteView>;

export function GetPreferences():Promise<main.PreferencesView>;

export function GetSkyName():Promise<string>;

export function GetSkyPath():Promise<string>;

export function GetStats():Promise<main.StatsView>;

export function GetTrails():Promise<Array<main.TrailView>>;

export function GetWorkspaceState():Promise<store.WorkspaceState>;

export function ListFolders():Promise<Array<string>>;

export function MigrateSky():Promise<store.MigrateReport>;

export function MoveNote(arg1:string,arg2:string):Promise<void>;

export function OpenNote(arg1:string):Promise<main.NoteView>;

export function OpenSky(arg1:string):Promise<main.SkyStateView>;

export function PickFolder():Promise<string>;

export function RemoveKnownSky(arg1:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SavePreferences(arg1:main.PreferencesView):Promise<void>;

export function SaveWorkspaceState(arg1:store.WorkspaceState):Promise<void>;

export function ScanSky():Promise<Array<main.NoteView>>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function SetupSky(arg1:string,arg2:string):Promise<main.SkyStateView>;

export function SkipMigration():Promise<void>;

export function SkyState():Promise<main.SkyStateView>;

export function SwitchSky(arg1:string):Promise<string>;

export function WaterNote(arg1:string):Promise<boolean>;
