// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:string,arg2:string):Promise<main.NoteView>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetNote(arg1:string):Promise<main.NoteView|boolean>;

export function GetNotes():Promise<Array<main.NoteView>>;

export function GetPalette():Promise<main.PaletteView>;

export function GetStats():Promise<main.StatsView>;

export function GetTrails():Promise<Array<main.TrailView>>;

export function OpenNote(arg1:string):Promise<main.NoteView>;

export function SaveNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WaterNote(arg1:string):Promise<boolean>;
